created feature landing page"
kundajose/My-brand pull request #1
Opened 2022-11-28 17:29 UTC by kundajose

Uploading landing page

2022-11-29 17:34 UTC, kundajose commented
My website HTML CSS and form validation

2022-11-29 18:45 UTC, Eli250 requested changes
Remove  unnecessary lines and make sure that  you have only one commit message.

2022-11-29 18:45 UTC, Eli250 commented on script.js
> +
Remove unnecessary empty lines.

2022-12-02 07:10 UTC, kundajose commented on script.js
> +
I have removed it

2022-12-02 07:34 UTC, kundajose commented
Add log in validation ad removed unnecessary lines.

2022-12-02 08:33 UTC, Eli250 approved these changes

2022-12-02 08:33 UTC, merged